{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}-route
spec:
  host: {{ .Values.route.hostname }}
  to:
    kind: Service
    name: {{ .Values.name }}-service
{{- end }}
