replicaCount: 2
name: app-helm-chart
image:
  repository: nginx
  tag: latest
service:
  type: ClusterIP
config:
  exampleKey: "exampleValue"
storage:
  size: 1Gi
secret:
  username: "admin"
  password: "password"
